version: "2"
services:
  app:
    image: serafinframework/nodejs:dev
    command: "npm run-script dev"
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - .:/srv
      - /d/Arvymetal/.ssh/:/home/node/.ssh/:ro